import React from 'react';
import { View, Text, Image } from 'react-native';
import { colors } from '../theme/colors';



// Import all country flags as PNG
export const flagImages = {
  af: require('../assets/flags/af.png'),
  al: require('../assets/flags/al.png'),
  dz: require('../assets/flags/dz.png'),
  ad: require('../assets/flags/ad.png'),
  ag: require('../assets/flags/ag.png'),
  ar: require('../assets/flags/ar.png'),
  am: require('../assets/flags/am.png'),
  au: require('../assets/flags/au.png'),
  at: require('../assets/flags/at.png'),
  az: require('../assets/flags/az.png'),
  bs: require('../assets/flags/bs.png'),
  bh: require('../assets/flags/bh.png'),
  bd: require('../assets/flags/bd.png'),
  bb: require('../assets/flags/bb.png'),
  by: require('../assets/flags/by.png'),
  be: require('../assets/flags/be.png'),
  bz: require('../assets/flags/bz.png'),
  bj: require('../assets/flags/bj.png'),
  bt: require('../assets/flags/bt.png'),
  bo: require('../assets/flags/bo.png'),
  ba: require('../assets/flags/ba.png'),
  bw: require('../assets/flags/bw.png'),
  br: require('../assets/flags/br.png'),
  bn: require('../assets/flags/bn.png'),
  bg: require('../assets/flags/bg.png'),
  bf: require('../assets/flags/bf.png'),
  bi: require('../assets/flags/bi.png'),
  kh: require('../assets/flags/kh.png'),
  cm: require('../assets/flags/cm.png'),
  ca: require('../assets/flags/ca.png'),
  cv: require('../assets/flags/cv.png'),
  cf: require('../assets/flags/cf.png'),
  td: require('../assets/flags/td.png'),
  cl: require('../assets/flags/cl.png'),
  cn: require('../assets/flags/cn.png'),
  co: require('../assets/flags/co.png'),
  km: require('../assets/flags/km.png'),
  cg: require('../assets/flags/cg.png'),
  cd: require('../assets/flags/cd.png'),
  cr: require('../assets/flags/cr.png'),
  ci: require('../assets/flags/ci.png'),
  hr: require('../assets/flags/hr.png'),
  cu: require('../assets/flags/cu.png'),
  cy: require('../assets/flags/cy.png'),
  cz: require('../assets/flags/cz.png'),
  dk: require('../assets/flags/dk.png'),
  dj: require('../assets/flags/dj.png'),
  dm: require('../assets/flags/dm.png'),
  do: require('../assets/flags/do.png'),
  ec: require('../assets/flags/ec.png'),
  eg: require('../assets/flags/eg.png'),
  sv: require('../assets/flags/sv.png'),
  gq: require('../assets/flags/gq.png'),
  er: require('../assets/flags/er.png'),
  ee: require('../assets/flags/ee.png'),
  et: require('../assets/flags/et.png'),
  fj: require('../assets/flags/fj.png'),
  fi: require('../assets/flags/fi.png'),
  fr: require('../assets/flags/fr.png'),
  ga: require('../assets/flags/ga.png'),
  gm: require('../assets/flags/gm.png'),
  ge: require('../assets/flags/ge.png'),
  de: require('../assets/flags/de.png'),
  gh: require('../assets/flags/gh.png'),
  gr: require('../assets/flags/gr.png'),
  gd: require('../assets/flags/gd.png'),
  gt: require('../assets/flags/gt.png'),
  gn: require('../assets/flags/gn.png'),
  gw: require('../assets/flags/gw.png'),
  gy: require('../assets/flags/gy.png'),
  ht: require('../assets/flags/ht.png'),
  hn: require('../assets/flags/hn.png'),
  hu: require('../assets/flags/hu.png'),
  is: require('../assets/flags/is.png'),
  in: require('../assets/flags/in.png'),
  id: require('../assets/flags/id.png'),
  ir: require('../assets/flags/ir.png'),
  iq: require('../assets/flags/iq.png'),
  ie: require('../assets/flags/ie.png'),
  il: require('../assets/flags/il.png'),
  it: require('../assets/flags/it.png'),
  jm: require('../assets/flags/jm.png'),
  jp: require('../assets/flags/jp.png'),
  jo: require('../assets/flags/jo.png'),
  kz: require('../assets/flags/kz.png'),
  ke: require('../assets/flags/ke.png'),
  ki: require('../assets/flags/ki.png'),
  kp: require('../assets/flags/kp.png'),
  kr: require('../assets/flags/kr.png'),
  kw: require('../assets/flags/kw.png'),
  kg: require('../assets/flags/kg.png'),
  la: require('../assets/flags/la.png'),
  lv: require('../assets/flags/lv.png'),
  lb: require('../assets/flags/lb.png'),
  ls: require('../assets/flags/ls.png'),
  lr: require('../assets/flags/lr.png'),
  ly: require('../assets/flags/ly.png'),
  li: require('../assets/flags/li.png'),
  lt: require('../assets/flags/lt.png'),
  lu: require('../assets/flags/lu.png'),
  mk: require('../assets/flags/mk.png'),
  mg: require('../assets/flags/mg.png'),
  mw: require('../assets/flags/mw.png'),
  my: require('../assets/flags/my.png'),
  ml: require('../assets/flags/ml.png'),
  mt: require('../assets/flags/mt.png'),
  mh: require('../assets/flags/mh.png'),
  mr: require('../assets/flags/mr.png'),
  mu: require('../assets/flags/mu.png'),
  mx: require('../assets/flags/mx.png'),
  fm: require('../assets/flags/fm.png'),
  md: require('../assets/flags/md.png'),
  mc: require('../assets/flags/mc.png'),
  mn: require('../assets/flags/mn.png'),
  me: require('../assets/flags/me.png'),
  ma: require('../assets/flags/ma.png'),
  mz: require('../assets/flags/mz.png'),
  mm: require('../assets/flags/mm.png'),
  na: require('../assets/flags/na.png'),
  nr: require('../assets/flags/nr.png'),
  np: require('../assets/flags/np.png'),
  nl: require('../assets/flags/nl.png'),
  nz: require('../assets/flags/nz.png'),
  ni: require('../assets/flags/ni.png'),
  ne: require('../assets/flags/ne.png'),
  ng: require('../assets/flags/ng.png'),
  no: require('../assets/flags/no.png'),
  om: require('../assets/flags/om.png'),
  pk: require('../assets/flags/pk.png'),
  pw: require('../assets/flags/pw.png'),
  pa: require('../assets/flags/pa.png'),
  pg: require('../assets/flags/pg.png'),
  py: require('../assets/flags/py.png'),
  pe: require('../assets/flags/pe.png'),
  ph: require('../assets/flags/ph.png'),
  pl: require('../assets/flags/pl.png'),
  pt: require('../assets/flags/pt.png'),
  qa: require('../assets/flags/qa.png'),
  ro: require('../assets/flags/ro.png'),
  ru: require('../assets/flags/ru.png'),
  rw: require('../assets/flags/rw.png'),
  kn: require('../assets/flags/kn.png'),
  lc: require('../assets/flags/lc.png'),
  vc: require('../assets/flags/vc.png'),
  ws: require('../assets/flags/ws.png'),
  sm: require('../assets/flags/sm.png'),
  st: require('../assets/flags/st.png'),
  sa: require('../assets/flags/sa.png'),
  sn: require('../assets/flags/sn.png'),
  rs: require('../assets/flags/rs.png'),
  sc: require('../assets/flags/sc.png'),
  sl: require('../assets/flags/sl.png'),
  sg: require('../assets/flags/sg.png'),
  sk: require('../assets/flags/sk.png'),
  si: require('../assets/flags/si.png'),
  sb: require('../assets/flags/sb.png'),
  so: require('../assets/flags/so.png'),
  za: require('../assets/flags/za.png'),
  ss: require('../assets/flags/ss.png'),
  es: require('../assets/flags/es.png'),
  lk: require('../assets/flags/lk.png'),
  sd: require('../assets/flags/sd.png'),
  sr: require('../assets/flags/sr.png'),
  sz: require('../assets/flags/sz.png'),
  se: require('../assets/flags/se.png'),
  ch: require('../assets/flags/ch.png'),
  sy: require('../assets/flags/sy.png'),
  tj: require('../assets/flags/tj.png'),
  tz: require('../assets/flags/tz.png'),
  th: require('../assets/flags/th.png'),
  tl: require('../assets/flags/tl.png'),
  tg: require('../assets/flags/tg.png'),
  to: require('../assets/flags/to.png'),
  tt: require('../assets/flags/tt.png'),
  tn: require('../assets/flags/tn.png'),
  tr: require('../assets/flags/tr.png'),
  tm: require('../assets/flags/tm.png'),
  tv: require('../assets/flags/tv.png'),
  ug: require('../assets/flags/ug.png'),
  ua: require('../assets/flags/ua.png'),
  ae: require('../assets/flags/ae.png'),
  gb: require('../assets/flags/gb.png'),
  us: require('../assets/flags/us.png'),
  uy: require('../assets/flags/uy.png'),
  uz: require('../assets/flags/uz.png'),
  vu: require('../assets/flags/vu.png'),
  va: require('../assets/flags/va.png'),
  ve: require('../assets/flags/ve.png'),
  vn: require('../assets/flags/vn.png'),
  ye: require('../assets/flags/ye.png'),
  zm: require('../assets/flags/zm.png'),
  zw: require('../assets/flags/zw.png'),
  mo: require('../assets/flags/mo.png'),
  hk: require('../assets/flags/hk.png'),
  tw: require('../assets/flags/tw.png'),
  xk: require('../assets/flags/xk.png'),
  an: require('../assets/flags/an.png'),
  ai: require('../assets/flags/ai.png'),
  bm: require('../assets/flags/bm.png'),
  bq: require('../assets/flags/bq.png'),
  cw: require('../assets/flags/cw.png'),
  gf: require('../assets/flags/gf.png'),
  ky: require('../assets/flags/ky.png'),
  mq: require('../assets/flags/mq.png'),
  ms: require('../assets/flags/ms.png'),
  tc: require('../assets/flags/tc.png'),
  vg: require('../assets/flags/vg.png'),
  ax: require('../assets/flags/ax.png'),
  gg: require('../assets/flags/gg.png'),
  gi: require('../assets/flags/gi.png'),
  gl: require('../assets/flags/gl.png'),
  im: require('../assets/flags/im.png'),
  je: require('../assets/flags/je.png'),
  pr: require('../assets/flags/pr.png'),
  re: require('../assets/flags/re.png'),
  fo: require('../assets/flags/fo.png'),
  aw: require('../assets/flags/aw.png'),
  gp: require('../assets/flags/gp.png'),
  pf: require('../assets/flags/pf.png'),
  ic: require('../assets/flags/ic.png'),
  ps: require('../assets/flags/ps.png'),
};

export const countries = [
  { id: 'af', name: 'Afghanistan' },
  { id: 'ax', name: 'Aland Islands' },
  { id: 'al', name: 'Albania' },
  { id: 'dz', name: 'Algeria' },
  { id: 'ad', name: 'Andorra' },
  { id: 'ai', name: 'Anguilla' },
  { id: 'ag', name: 'Antigua and Barbuda' },
  { id: 'ar', name: 'Argentina' },
  { id: 'am', name: 'Armenia' },
 { id: 'aw', name: 'Aruba' },
  { id: 'au', name: 'Australia' },
  { id: 'at', name: 'Austria' },
  { id: 'az', name: 'Azerbaijan' },
  { id: 'bs', name: 'Bahamas' },
  { id: 'bh', name: 'Bahrain' },
  { id: 'bd', name: 'Bangladesh' },
  { id: 'bb', name: 'Barbados' },
  { id: 'by', name: 'Belarus' },
  { id: 'be', name: 'Belgium' },
  { id: 'bz', name: 'Belize' },
  { id: 'bj', name: 'Benin' },
  { id: 'bm', name: 'Bermuda' },
  { id: 'bt', name: 'Bhutan' },
  { id: 'bo', name: 'Bolivia' },
  { id: 'bq', name: 'Bonaire' },
  { id: 'ba', name: 'Bosnia and Herzegovina' },
  { id: 'bw', name: 'Botswana' },
  { id: 'br', name: 'Brazil' },
  { id: 'bn', name: 'Brunei' },
  { id: 'bg', name: 'Bulgaria' },
  { id: 'bf', name: 'Burkina Faso' },
  { id: 'bi', name: 'Burundi' },
  { id: 'kh', name: 'Cambodia' },
  { id: 'cm', name: 'Cameroon' },
  { id: 'ca', name: 'Canada' },
  { id: 'ic', name: 'Canary Islands' },
  { id: 'cv', name: 'Cape Verde' },
  { id: 'ky', name: 'Cayman Islands' },
  { id: 'cf', name: 'Central African Republic' },
  { id: 'td', name: 'Chad' },
  { id: 'cl', name: 'Chile' },
  { id: 'cn', name: 'China' },
  { id: 'co', name: 'Colombia' },
  { id: 'km', name: 'Comoros' },
  { id: 'cg', name: 'Congo' },
  { id: 'cd', name: 'Congo Democratic Republic' },
  { id: 'cr', name: 'Costa Rica' },
  { id: 'ci', name: "Côte d'Ivoire" },
  { id: 'hr', name: 'Croatia' },
  { id: 'cu', name: 'Cuba' },
  { id: 'cw', name: 'Curaçao' },
  { id: 'cy', name: 'Cyprus' },
  { id: 'cz', name: 'Czech Republic' },
  { id: 'dk', name: 'Denmark' },
  { id: 'dj', name: 'Djibouti' },
  { id: 'dm', name: 'Dominica' },
  { id: 'do', name: 'Dominican Republic' },
  { id: 'ec', name: 'Ecuador' },
  { id: 'eg', name: 'Egypt' },
  { id: 'sv', name: 'El Salvador' },
  { id: 'gq', name: 'Equatorial Guinea' },
  { id: 'er', name: 'Eritrea' },
  { id: 'ee', name: 'Estonia' },
  { id: 'sz', name: 'Eswatini' },
  { id: 'et', name: 'Ethiopia' },
 { id: 'fj', name: 'Fiji' },
  { id: 'fo', name: 'Faroe Islands' },
  { id: 'fi', name: 'Finland' },
  { id: 'fr', name: 'France' },
  { id: 'gf', name: 'French Guiana' },
  { id: 'pf', name: 'French Polynesia' },
  { id: 'ga', name: 'Gabon' },
  { id: 'gm', name:  'Gambia' },
  { id: 'ge', name: 'Georgia' },
  { id: 'de', name: 'Germany' },
  { id: 'gh', name: 'Ghana' },
  { id: 'gi', name: 'Gibraltar' },
  { id: 'gr', name: 'Greece' },
  { id: 'gl', name: 'Greenland' },
  { id: 'gd', name: 'Grenada' },
  { id: 'gp', name: 'Guadeloupe' },
  { id: 'gt', name: 'Guatemala' },
  { id: 'gg', name: 'Guernsey' },
  { id: 'gn', name: 'Guinea' },
  { id: 'gw', name: 'Guinea-Bissau' },
  { id: 'gy', name: 'Guyana' },
  { id: 'ht', name: 'Haiti' },
  { id: 'hk', name: 'Hong Kong' },
  { id: 'hn', name: 'Honduras' },
  { id: 'hu', name: 'Hungary' },
  { id: 'is', name: 'Iceland' },
  { id: 'in', name: 'India' },
  { id: 'id', name: 'Indonesia' },
  { id: 'ir', name: 'Iran' },
  { id: 'iq', name: 'Iraq' },
  { id: 'ie', name: 'Ireland' },
  { id: 'im', name: 'Isle of Man' },
  { id: 'il', name: 'Israel' },
  { id: 'it', name: 'Italy' },
  { id: 'jm', name: 'Jamaica' },
  { id: 'jp', name: 'Japan' },
  { id: 'je', name: 'Jersey' },
  { id: 'jo', name: 'Jordan' },
  { id: 'kz', name: 'Kazakhstan' },
  { id: 'ke', name: 'Kenya' },
  { id: 'ki', name: 'Kiribati' },
  { id: 'xk', name: 'Kosovo' },
  { id: 'kw', name: 'Kuwait' },
  { id: 'kg', name: 'Kyrgyzstan' },
  { id: 'la', name: 'Laos' },
  { id: 'lv', name: 'Latvia' },
  { id: 'lb', name: 'Lebanon' },
  { id: 'ls', name: 'Lesotho' },
  { id: 'lr', name: 'Liberia' },
  { id: 'ly', name: 'Libya' },
  { id: 'li', name: 'Liechtenstein' },
  { id: 'lt', name: 'Lithuania' },
  { id: 'lu', name: 'Luxembourg' },
  { id: 'mo', name: 'Macao' },
  { id: 'mg', name: 'Madagascar' },
  { id: 'mw', name: 'Malawi' },
  { id: 'my', name: 'Malaysia' },
  { id: 'ml', name: 'Mali' },
  { id: 'mt', name: 'Malta' },
  { id: 'mh', name: 'Marshall Islands' },
  { id: 'mq', name: 'Martinique' },
  { id: 'mr', name: 'Mauritania' },
  { id: 'mu', name: 'Mauritius' },
  { id: 'mx', name: 'Mexico' },
  { id: 'fm', name: 'Micronesia' },
  { id: 'md', name: 'Moldova' },
  { id: 'mc', name: 'Monaco' },
  { id: 'mn', name: 'Mongolia' },
  { id: 'me', name: 'Montenegro' },
  { id: 'ms', name: 'Montserrat' },
  { id: 'ma', name: 'Morocco' },
  { id: 'mz', name: 'Mozambique' },
  { id: 'mm', name: 'Myanmar' },
  { id: 'na', name: 'Namibia' },
  { id: 'nr', name: 'Nauru' },
  { id: 'np', name: 'Nepal' },
  { id: 'nl', name: 'Netherlands' },
  { id: 'an', name: 'Netherlands Antilles' },
  { id: 'nz', name: 'New Zealand' },
  { id: 'ni', name: 'Nicaragua' },
  { id: 'ne', name: 'Niger' },
  { id: 'ng', name: 'Nigeria' },
  { id: 'kp', name: 'North Korea' },
  { id: 'mk', name: 'North Macedonia' },
  { id: 'no', name: 'Norway' },
  { id: 'om', name: 'Oman' },
  { id: 'pk', name: 'Pakistan' },
  { id: 'pw', name: 'Palau' },
  { id: 'ps', name: 'Palestine' },
  { id: 'pa', name: 'Panama' },
  { id: 'pg', name: 'Papua New Guinea' },
  { id: 'py', name: 'Paraguay' },
  { id: 'pe', name: 'Peru' },
  { id: 'ph', name: 'Philippines' },
  { id: 'pl', name: 'Poland' },
  { id: 'pt', name: 'Portugal' },
  { id: 'pr', name: 'Puerto Rico' },
  { id: 'qa', name: 'Qatar' },
  { id: 're', name: 'Reunion' },
  { id: 'ro', name: 'Romania' },
  { id: 'ru', name: 'Russia' },
  { id: 'rw', name: 'Rwanda' },
  { id: 'kn', name: 'Saint Kitts and Nevis' },
  { id: 'lc', name: 'Saint Lucia' },
  { id: 'vc', name: 'Saint Vincent and the Grenadines' },
  { id: 'ws', name: 'Samoa' },
  { id: 'sm', name: 'San Marino' },
  { id: 'st', name: 'Sao Tome and Principe' },
  { id: 'sa', name: 'Saudi Arabia' },
  { id: 'sn', name: 'Senegal' },
  { id: 'rs', name: 'Serbia' },
  { id: 'sc', name: 'Seychelles' },
  { id: 'sl', name: 'Sierra Leone' },
  { id: 'sg', name: 'Singapore' },
  { id: 'sk', name: 'Slovakia' },
  { id: 'si', name: 'Slovenia' },
  { id: 'sb', name: 'Solomon Islands' },
  { id: 'so', name: 'Somalia' },
  { id: 'za', name: 'South Africa' },
  { id: 'kr', name: 'South Korea' },
  { id: 'ss', name: 'South Sudan' },
  { id: 'es', name: 'Spain' },
  { id: 'lk', name: 'Sri Lanka' },
  { id: 'sd', name: 'Sudan' },
  { id: 'sr', name: 'Suriname' },
  { id: 'se', name: 'Sweden' },
  { id: 'ch', name: 'Switzerland' },
  { id: 'sy', name: 'Syria' },
  { id: 'tj', name: 'Tajikistan' },
  { id: 'tz', name: 'Tanzania' },
  { id: 'th', name: 'Thailand' },
  { id: 'tw', name: 'Taiwan' },
  { id: 'tl', name: 'Timor-Leste' },
  { id: 'tg', name: 'Togo' },
  { id: 'to', name: 'Tonga' },
  { id: 'tt', name: 'Trinidad and Tobago' },
  { id: 'tn', name: 'Tunisia' },
  { id: 'tr', name: 'Turkey' },
  { id: 'tm', name: 'Turkmenistan' },
  { id: 'tc', name: 'Turks and Caicos Islands' },
  { id: 'tv', name: 'Tuvalu' },
  { id: 'ug', name: 'Uganda' },
  { id: 'ua', name: 'Ukraine' },
  { id: 'ae', name: 'United Arab Emirates' },
  { id: 'gb', name: 'United Kingdom' },
  { id: 'us', name: 'United States' },
  { id: 'uy', name: 'Uruguay' },
  { id: 'uz', name: 'Uzbekistan' },
  { id: 'vu', name: 'Vanuatu' },
  { id: 'va', name: 'Vatican City' },
  { id: 've', name: 'Venezuela' },
  { id: 'vn', name: 'Vietnam' },
  { id: 'vg', name: 'Virgin Islands' },
  { id: 'ye', name: 'Yemen' },
  { id: 'zm', name: 'Zambia' },
  { id: 'zw', name: 'Zimbabwe' },
];

export const FlagIcon = React.memo(({ countryCode, size = 30, variant = 'default' }) => {
  const getBorderStyle = () => {
    if (variant === 'popular') {
      return {
        borderWidth: 2,
        borderColor: colors.stone[400], // Slightly warmer stone color
        shadowColor: colors.stone[500],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2, // For Android shadow
      };
    }
    return {
      borderWidth: 1,
      borderColor: colors.stone[300], // Lighter stone for default
      shadowColor: colors.stone[400],
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1, // For Android shadow
    };
  };

  if (!countryCode) {
    return (
      <View style={[{
        width: size,
        height: size,
        borderRadius: size / 2,
        backgroundColor: colors.background.secondary,
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        ...getBorderStyle()
      }]}>
        <Text style={{ 
          fontSize: size / 2, 
          color: colors.text.secondary 
        }}>?</Text>
      </View>
    );
  }

  const normalizedCode = countryCode.toLowerCase();
  const flagImage = flagImages[normalizedCode];
  
  if (flagImage) {
    return (
      <View style={[{
        width: size,
        height: size,
        borderRadius: size / 2,
        backgroundColor: colors.background.secondary,
        overflow: 'hidden',
        ...getBorderStyle()
      }]}>
        <Image
          source={flagImage}
          style={{
            width: '100%',
            height: '100%',
            borderRadius: size / 2,
          }}
          resizeMode="cover"
        />
      </View>
    );
  }

  return (
    <View style={[{
      width: size,
      height: size,
      borderRadius: size / 2,
      backgroundColor: colors.background.secondary,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      ...getBorderStyle()
    }]}>
      <Text style={{ 
        fontSize: size / 3, 
        color: colors.text.secondary,
        fontFamily: 'Quicksand'
      }}>
        {countryCode.substring(0, 2).toUpperCase()}
      </Text>
    </View>
  );
});

// Also export as default for backward compatibility
export default {
  countries,
  flagImages,
  FlagIcon,
};