// globalCoverage.ts

export const globalCoverageCountries = [
  'Andorra',
  'United Arab Emirates',
  'Albania',
  'Armenia',
  'Antilles',
  'Argentina',
  'Austria',
  'Australia',
  'Aruba',
  'Azerbaijan',
  'Bangladesh',
  'Belgium',
  'Bulgaria',
  'Bahrain',
  'Brunei',
  'Bolivia',
  'Brazil',
  'Bahamas',
  'Belarus',
  'Belize',
  'Canada',
  'Congo Democratic Republic',
  'Congo',
  'Switzerland',
  'Côte d\'Ivoire',
  'Chile',
  'Cameroon',
  'China',
  'Colombia',
  'Costa Rica',
  'Northern Cyprus',
  'Czech Republic',
  'Germany',
  'Denmark',
  'Dominican Republic',
  'Algeria',
  'Ecuador',
  'Estonia',
  'Egypt',
  'Spain',
  'Finland',
  'Fiji',
  'Faroe Islands',
  'France',
  'Scotland',
  'Georgia',
  'Guernsey',
  'Ghana',
  'Gibraltar',
  'Gambia',
  'Guadeloupe',
  'Greece',
  'Guatemala',
  'Guyana',
  'Hong Kong',
  'Honduras',
  'Croatia',
  'Hungary',
  'Indonesia',
  'Ireland',
  'Israel',
  'India',
  'Iceland',
  'Italy',
  'Jersey',
  'Jamaica',
  'Jordan',
  'Japan',
  'Kenya',
  'Cambodia',
  'South Korea',
  'Kuwait',
  'Kazakhstan',
  'Liechtenstein',
  'Sri Lanka',
  'Liberia',
  'Lithuania',
  'Luxembourg',
  'Latvia',
  'Morocco',
  'Monaco',
  'Moldova',
  'Montenegro',
  'Madagascar',
  'North Macedonia',
  'Mali',
  'Mongolia',
  'Macao',
  'Malta',
  'Mexico',
  'Malaysia',
  'Mozambique',
  'Nigeria',
  'Nicaragua',
  'Netherlands',
  'Norway',
  'New Zealand',
  'Oman',
  'Panama',
  'Peru',
  'French Polynesia',
  'Philippines',
  'Pakistan',
  'Poland',
  'Puerto Rico',
  'Portugal',
  'Paraguay',
  'Qatar',
  'Réunion',
  'Romania',
  'Serbia',
  'Saudi Arabia',
  'Seychelles',
  'Sweden',
  'Singapore',
  'Slovenia',
  'Slovakia',
  'Sierra Leone',
  'Senegal',
  'Suriname',
  'El Salvador',
  'Thailand',
  'Timor - Leste',
  'Tunisia',
  'Turkey',
  'Trinidad and Tobago',
  'Taiwan',
  'Tanzania',
  'Ukraine',
  'Uganda',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'British Virgin Islands',
  'Vietnam',
  'South Africa'
];

// Helper function to check if a country is included in global coverage
export const isCountryInGlobalCoverage = (countryName: string): boolean => {
  return globalCoverageCountries.includes(countryName);
};

export default globalCoverageCountries;